### ISSUE TITLE
Java.Lang Fatal EXCEPTION

### ISSUE THREAD

**Issue by Volkanugr** [code-troopers/android-betterpickers#104]
my problem is not understanding

compile fileTree(dir: 'libs', include: ['*.jar'])
compile 'com.github.dmytrodanylyk.circular-progress-button:library:1.0.4'
compile 'info.hoang8f:fbutton:1.0.4'
compile 'com.romainpiel.shimmer:library:1.2.0@aar'
compile 'com.nhaarman.listviewanimations:library:2.6.0'
compile 'com.readystatesoftware.sqliteasset:sqliteassethelper:+'
compile 'com.actionbarsherlock:actionbarsherlock:4.4.0@aar'
and everything is good working

add compile 'com.doomonafireball.betterpickers:library:1.5.2'

and than
my application stopped to work on create FATAL EROR EXCEPTION why ?

**Comment by Volkanugr** [comment]
i fixed my asset has a fonts directory and i delete it work !

**Comment by bbbenja** [comment]
If this is fixed, I close
