### ISSUE TITLE
Can't access setThemeDark for RadialTimePickerDialog

### ISSUE THREAD

**Issue by coreyog** [code-troopers/android-betterpickers#105]
Fully explained here: http://stackoverflow.com/questions/24846786/betterpickers-isnt-building-with-setthemedark-for-radialtimepicker

In short, no matter how I add the library to Android Studio, setThemeDark isn't available for the RadialTimePickerDialog.

**Comment by fchauveau** [comment]
Hi @coreyog 
This have been done via PR #198
And released in 2.2.0
