### ISSUE TITLE
Resource name collision

### ISSUE THREAD

**Issue by zhanghai** [code-troopers/android-betterpickers#107]
The `values/colors.xml` stated color names including `blue`, `darker_blue`, etc, which get overridden if user has his own `blue` specified in his own `values/colors.xml`. This is because Android make user's resource take precedence when a naming conflict happens.

Can you refactor all the color resource names, for example adding the prefix of `bp_`(for betterpickers) as a namespace, so that these resources can function as expected?

**Comment by emileb** [comment]
Did you fix this? I have added it to my Android Studio project and it's going on about clashing color names which don't make any sense at all, the names don't match anything in my color.xml.

**Comment by fchauveau** [comment]
I'm going to prefix all color resouces with `bp` this week

**Comment by CedricGatay** [comment]
Closing as a fix as been merged and not further comment made
