### ISSUE TITLE
“Native typeface cannot be made” error when importing in eclipse

### ISSUE THREAD

**Issue by mmathys** [code-troopers/android-betterpickers#110]
Some people might see this error:
java.lang.RuntimeException: native typeface cannot be made

This Exception is thrown because the assets folder is not copied into the parent project, so the library project fails to load the corresponding fonts. I don't know whether there is a workaround out there, neither I know how you can create one.

**Comment by fchauveau** [comment]
Everybody is now using android studio, so this issue can be closed
