### ISSUE TITLE
Translation in Spanish is only partly done

### ISSUE THREAD

**Issue by yamidragut** [code-troopers/android-betterpickers#114]
Hi, 

The Spanish translation is only partly done, are you going to fully translate the library to Spanish? 

Thanks a lot!

**Comment by CedricGatay** [comment]
Hi,
actually nobody in the team speaks Spanish, but feel free to provide a pull request with the missing translations.

Regards,

**Comment by fchauveau** [comment]
Hi @yamidragut 

any chance that you provide Spanish translations ?
