### ISSUE TITLE
Is it possible to use the library without android.support.v4?

### ISSUE THREAD

**Issue by yyunikov** [code-troopers/android-betterpickers#116]
I would like to use the library, but I don't use `android.support.v4` in my fragments and activities I use the standard fragment classes from `android.app` package. For instance, methods in the library like `setFragmentManager(android.support.v4.app.FragmentManager manager)` require `android.support.v4.app.FragmentManager`, however I use the `android.app.FragmentManager`. Do you have any support for that?

**Comment by paulroehr** [comment]
There is a Pull Request which replaces the support Fragments with the native Fragments:

https://github.com/derekbrameyer/android-betterpickers/pull/73

**Comment by yyunikov** [comment]
Awesome, thanks.

**Comment by gpulido** [comment]
Hello,
Is this pull request going to be merged anytime soon?
I need to use the library inside a native fragment and I would like to avoid rewriting or using the pull request as a patch.

Thank you

**Comment by fchauveau** [comment]
Hi @gpulido 

Yes we are working on removing appcompat v4 and also removing switch backport dependencies.
This update should come at the end of june.

A snapshot version will be publish on sonatype in few weeks

**Comment by gpulido** [comment]
Awesome!
Thank you for your great work and support!

**Comment by ZOlbrys** [comment]
Any update on the native fragment support? I'd love to use this library on my project, but I'm not using the support fragments! Thanks!

**Comment by zhanghai** [comment]
You can checkout my fork https://github.com/DreaminginCodeZH/betterpickers . It uses native Fragment, native Switch and gradle build. I've been using it in one of my production app for half a year.

However, I still strongly recommend the use of support Fragment - it is the way to go. I did that fork because at that time I did not realize this.

**Comment by fchauveau** [comment]
Hi @ZOlbrys 

Now betterpickers only use _com.android.support:appcompat-v7_
It's required for Switch button in some recurrence picker, and it's not plan to remove it. So we could not help you on this point.
