### ISSUE TITLE
NumberPickerDialogBuilder is missing a method to set initial picker value

### ISSUE THREAD

**Issue by davidschreiber** [code-troopers/android-betterpickers#118]
Currently NumberPickerDialog does not support editing an existing value (or simply pre-filling the picker). An extra method for the builder, e.g. `builder.setValue(10.4)`, would be necessary to accomplish this.

**Comment by CedricGatay** [comment]
Looks cool to me.

Feel free to deep dive into the code and add the method you suggest.

**Comment by fchauveau** [comment]
Hi @davidschreiber
I'm working on it, should be soon available.

**Comment by fchauveau** [comment]
@davidschreiber merged, will be released in 1.5.6

**Comment by davidschreiber** [comment]
Thanks a lot!
