### ISSUE TITLE
Gettint lot of crashes

### ISSUE THREAD

**Issue by kunalsharma** [code-troopers/android-betterpickers#119]
Hi, 
I am getting lot of crashed  one of my crash is 

android.view.InflateException: Binary XML file line #7: Error inflating class com.doomonafireball.betterpickers.datepicker.DatePicker

thanks

**Comment by drupalmav** [comment]
were you able to find a fix to this issue? I am getting the same error for the same line#

**Comment by CedricGatay** [comment]
Without further details this issue will be closed.
