### ISSUE TITLE
Conflicts with new AppCompat v7 21.0.0

### ISSUE THREAD

**Issue by AaronRietschlin** [code-troopers/android-betterpickers#120]
The use of the switch back port is causing a styling conflict.

**Comment by DDRBoxman** [comment]
Already opened a pull request with a fix here: #121

**Comment by TomMaddox** [comment]
Thanks for the PR @DDRBoxman - This was the end of a head-scratching session for me!

**Comment by dexafree** [comment]
Thanks for the PR @DDRBoxman 

Please @derekbrameyer accept the PR

**Comment by alopix** [comment]
This could also be resolved by using http://developer.android.com/reference/android/support/v7/widget/SwitchCompat.html instead of the custom implementation ;)

**Comment by adrian-chang** [comment]
This project seems a little dead to me, the owner has made 2 contributions in like the last 6 months. Can someone fork it? Or hopefully the owner gives some other people control...

**Comment by TomMaddox** [comment]
Correct me if I'm wrong @alopix, but SwitchCompat only offers toggle switch, not a number picking dialog like this library provides

**Comment by alopix** [comment]
@TomMaddox I was referring to the Switch backport, not the whole project ;)

**Comment by TriPSs** [comment]
Is this already fixed?

**Comment by derekbrameyer** [comment]
Hi guys, you're right, I don't have the time to dedicate to this project anymore.  It's unfortunate but such is life sometimes.  If any of you are interested in maintaining this, please contact me via e-mail (derek.brameyer@gmail.com).  Sorry!

**Comment by TriPSs** [comment]
Could you atleast accept his pull request so it works with appcompat ?

**Comment by jschnall** [comment]
Also need this, please.

**Comment by TriPSs** [comment]
Does some one has a working version uploaded to gradle?

**Comment by T0bbes** [comment]
pls accept this request.. ;)

**Comment by TriPSs** [comment]
For all the people in need:
https://mega.co.nz/#!EolzzAIT!z2N4Oag7RhkvTQbhyGQc3_ryDyEQ7da1tmwRdiEc9JI
Invluce this and it should work again.

**Comment by StErMi** [comment]
Hi guys, someone know when it will be updated on gradle?

**Comment by zhanghai** [comment]
Not until someone else pick up this project. I have  been using my homebrew version for a while.

**Comment by Tooto** [comment]
@TriPSs u lost sdk 9 support( sad

**Comment by TriPSs** [comment]
@Tooto I changed that because i rememberd reading somwhere that if you include aar it has to be the same apk level as your application.
Here's one with level 9
https://mega.co.nz/#!d1VxQShL!evoYJGkGvCrAF8VmuuuDiwW_0wvCI3ONR-YztDJA59k

**Comment by SimplyY** [comment]
I use gradle to build, but the change of the lasted commit(c71397a9) hasn't make sense in my code. The question about #129 still exsit .For example ,in my code,  "track" still is "track" not "dptrack"(in library/res/values/attrs.xml is dptrack)

**Comment by CedricGatay** [comment]
Hi @SimplyY,
I have a local build for now of 1.5.3-SNAPSHOT and tested against a few projects, that seems to work as expected. The attributes are renamed from `track` to `bpTrack` for example.
Please make sure you don't have jraf's switch backport in your dependencies along the one bundled in betterpickers.

**Comment by CedricGatay** [comment]
I have uploaded a SNAPSHOT version of the 1.5.3 to Sonatype Central, please add this url to your maven repositories and test it before promotion : https://oss.sonatype.org/content/repositories/snapshots/

**Comment by CedricGatay** [comment]
1.5.3 is now released, feel free to update your dependency to use it, you should not have any problem with appcompat 21 now (you will need to prefix some style attributes with bp though)

**Comment by StringMon** [comment]
I'm still experiencing this using betterpickers v1.5.4:

Error:(1) Attribute "track" has already been defined
Error:(1) Attribute "thumbTextPadding" has already been defined
Error:(1) Attribute "switchTextAppearance" has already been defined
Error:(1) Attribute "switchMinWidth" has already been defined
Error:(1) Attribute "switchPadding" has already been defined
Error:(1) Attribute "switchStyle" has already been defined

FWIW, here's the relevant section from my build.gradle:

```
dependencies {
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile ("com.doomonafireball.betterpickers:library:1.5.4") {
        exclude group: 'com.android.support', module: 'appcompat-v7'
    }
}
```

@CedricGatay how do I go about prefixing style attributes?

**Comment by smaspe** [comment]
@StringMon Had the same issue, replaced version with 1.5.3, seems to compile so far using

```
compile ("com.doomonafireball.betterpickers:library:1.5.3")
```

@CedricGatay possibly a regression?

**Comment by CedricGatay** [comment]
@smaspe I think it is. We will look after it ASAP and release a 1.5.5 with a fix. Sorry guys
