### ISSUE TITLE
1.5.2 not working with support-v4:21.0.+

### ISSUE THREAD

**Issue by jschnall** [code-troopers/android-betterpickers#124]
The notes for 1.5.2 say they should fix this issue.  I was already using 1.5.2 without the exclusion, but when I upgraded the support lib started seeing...

Error:Attribute "track" has already been defined
Error:Attribute "thumbTextPadding" has already been defined
etc.

This happens whether I exclude support v4 in build.gradle or not.  I've tried cleaning, rebuilding, resyncing gradle numerous times... pretty much everything I could think of.  :-(

Any help you could provide would be appreciated.

**Comment by jschnall** [comment]
Figured out this was actually a similar naming conflict due to appcompat-v7.  There are other fixes waiting to be merged already, so will just close.

**Comment by Thamizhan** [comment]
Still not resolved, I'm getting the same error when I try this today

**Comment by StErMi** [comment]
Got the same error and I'm using v1.5.2 from gradle

**Comment by BilalBoulifa** [comment]
I have the same error to

**Comment by mkaarthick** [comment]
I have the same error. Is there any working solution?

**Comment by CedricGatay** [comment]
Hi everyone, we are currently in the process of transfering project management to our team. 

We are doing our best to update the library to work with AppCompat21 in a short matter of time, but with end of year holidays you have to be patient. 

It's coming for early 2015 !
