### ISSUE TITLE
Getting error after adding the library

### ISSUE THREAD

**Issue by ranjithnair02** [code-troopers/android-betterpickers#126]
There is conflict in my project when I try to use this library with compile betterpickers library. Gradle report following error:

Error:Attribute "track" has already been defined
Error:Attribute "thumbTextPadding" has already been defined
Error:Attribute "switchTextAppearance" has already been defined
Error:Attribute "switchMinWidth" has already been defined
Error:Attribute "switchPadding" has already been defined
Error:Attribute "switchStyle" has already been defined been defined

I have heme.AppCompat.Light as my app theme.

**Comment by T0bbes** [comment]
#120

**Comment by CedricGatay** [comment]
I second @T0bbes, the proposed PR is on its way to a release soon.

**Comment by cesarferreira** [comment]
is this issue really fixed? It happens to me

my dependencies
<code>
  compile 'com.android.support:appcompat-v7:22.0.0'

```
compile ("com.doomonafireball.betterpickers:library:1.5.4") {
    exclude group: 'com.android.support', module: 'appcompat-v7'
    exclude group: 'com.android.support', module: 'support-v7'
}
```

</code>

**Comment by gatlingxyz** [comment]
This issue is NOT fixed.

**Comment by CedricGatay** [comment]
We will release 1.5.5 soon that hopefully should fix it

**Comment by CedricGatay** [comment]
@kentarosu @cesarferreira if you could provide the error message you've got it could help us to be sure we've fixed the mess.

**Comment by gatlingxyz** [comment]
I'm getting the exact same error as @ranjithnair02 (OP)

**Comment by CedricGatay** [comment]
Thanks for your fast reply, if we deploy a 1.5.5-SNAPSHOT on sonatype's snapshot repository will you be able to test your project with it ? It should be ok but we never know...

**Comment by gatlingxyz** [comment]
Yup, I'm ready and able.

**Comment by CedricGatay** [comment]
1.5.5-SNAPSHOT is up on Sonatype OSS Snapshot repositories (https://oss.sonatype.org/service/local/repositories/snapshots/content/com/doomonafireball/betterpickers/library/1.5.5-SNAPSHOT/library-1.5.5-20150325.072533-1.aar), could you give it a try @kentarosu please ?

**Comment by fchauveau** [comment]
Hi @kentarosu version 1.5.5 is released. 
Can you confirm that is fixing this issue ?

**Comment by CedricGatay** [comment]
Without news I consider this fixed. Closing the issue.
