### ISSUE TITLE
attributes already defined

### ISSUE THREAD

**Issue by BilalBoulifa** [code-troopers/android-betterpickers#129]
I'am getting this error when tring to compile

Error:Attribute "track" has already been defined
Error:Attribute "thumbTextPadding" has already been defined
Error:Attribute "switchTextAppearance" has already been defined
Error:Attribute "switchMinWidth" has already been defined
Error:Attribute "switchPadding" has already been defined
Error:Attribute "switchStyle" has already been defined

my dependencies are:

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile 'com.android.support:support-v4:21.0.+'
    compile 'com.android.support:cardview-v7:21.0.+'
    compile ("com.doomonafireball.betterpickers:library:1.5.2") {
        exclude group: 'com.android.support', module: 'support-v4'
    }
    compile project(':materialDesign')
}

**Comment by Tooto** [comment]
same problem

**Comment by CedricGatay** [comment]
Duplicate for #120, we will soon release a fix.
