### ISSUE TITLE
Islamic Month Names 

### ISSUE THREAD

**Issue by abodehq** [code-troopers/android-betterpickers#133]
Elslam alykom...Great work Guys.

I wanted to ask if i wanted to add the arabic month names to your library how can i do that??!!

can i pass string array that contains month names to library >>

wish you can helpp me in this.

**Comment by fchauveau** [comment]
I @abodehq fell free to create a PR with a new directory for your country translation into res folder

**Comment by CedricGatay** [comment]
Closing as inactive issue
