### ISSUE TITLE
can't find classes com.nineoldandroids.*

### ISSUE THREAD

**Issue by chenchongyu** [code-troopers/android-betterpickers#135]

**Comment by bbbenja** [comment]
Can you detail this error ?

**Comment by chenchongyu** [comment]
I solved this problem by import NineOldAndroids.thank you.Your project didn't say that,did it ?

**Comment by bbbenja** [comment]
This dependency is include in the `pom.xml` of the library so you should not have this issue.

```
<dependency>
            <groupId>com.nineoldandroids</groupId>
            <artifactId>library</artifactId>
            <version>2.4.0</version>
</dependency>
```

Check that you don't exclude it in your projet.
