### ISSUE TITLE
Major - RecurrenceDatePicker: Until Date in RRule is returning +1

### ISSUE THREAD

**Issue by BinaryShrub** [code-troopers/android-betterpickers#138]
Repro Steps:
Choose a date to end on for any reocurrencedatepicker frequency: in this case I chose 2/26
![screen shot 2015-01-24 at 7 54 29 pm](https://cloud.githubusercontent.com/assets/10691501/5890153/de817b56-a402-11e4-94fa-578d35688410.png)

The date that is returned in the rrule is actually the day after the one you selected: the timestamp is returning as 2/27
![screen shot 2015-01-24 at 7 54 36 pm](https://cloud.githubusercontent.com/assets/10691501/5890155/092c6438-a403-11e4-8123-300335a65373.png)

**Comment by BinaryShrub** [comment]
A workaround I have been using is to parse the String rrule that is returned and subtract a day from it.

**Comment by bbbenja** [comment]
Until date is converted to UTC timezone, so according of your timezone, you can have the day before or after the chosen day. Moreover, the hour/minute/second fields of the selected date in the calendar picker are setted according to the time when we made the action.

So I guess the simplest solution is to convert the date according to your timezone.
