### ISSUE TITLE
RecurrencePicker null pointer exception

### ISSUE THREAD

**Issue by BinaryShrub** [code-troopers/android-betterpickers#139]
Set it to month, and to day of week. The sample app will crash (my app will too):

java.lang.NullPointerException: Attempt to read from field 'int android.text.format.Time.weekDay' on a null object reference
            at com.doomonafireball.betterpickers.recurrencepicker.EventRecurrenceFormatter.getRepeatString(EventRecurrenceFormatter.java:106)

**Comment by bbbenja** [comment]
If you want to resolve it quickly, you can set the `startDate` on the `EventRecurrence` model.

We are working to resolve this issue.
