### ISSUE TITLE
Support min date in calendar date picker

### ISSUE THREAD

**Issue by smaspe** [code-troopers/android-betterpickers#144]
min date support was added in https://android.googlesource.com/platform/frameworks/opt/datetimepicker/+/7c597aee285f2fe4a13a24334493c6eadddd7939%5E%21/#F2

Please add support for this feature.

**Comment by fchauveau** [comment]
I'll look after that as soon as possible.
If you have time feel free to create a PR for that.

**Comment by robotomeister** [comment]
This would be a welcome feature since it's not only mindate but also maxdate as well.

**Comment by fchauveau** [comment]
Hi @robotomeister 

this feature in now avaiable see #200 and #202
