### ISSUE TITLE
Adding gradle to project gives R cannot be resolved issue

### ISSUE THREAD

**Issue by gauravjot** [code-troopers/android-betterpickers#145]
Its very annoying that adding the library in project gives R error saying that variable it cannot be resolved. My project is a very new project and just used the most recent of your gradle configuration. Please fix the issue fast, I love your library...

[I also tried a jar file from internet sources saying v1.5.3 and open in my android studio, surprisingly every single .java file of your project is giving "R" error and also fail to get "DatePicker" which is also unable to resolve according to android studio]

**Comment by CedricGatay** [comment]
Sorry I don't understand what your problem is. We're working hard on resolving the conflicts with Jraf actually.

Could you be more precise on what's working or not please ?

**Comment by CedricGatay** [comment]
Closing as no answer
