### ISSUE TITLE
Change color? RadialTimePickerDialog and CalendarDatePickerDialog

### ISSUE THREAD

**Issue by Rainer-Lang** [code-troopers/android-betterpickers#147]
How could the color be changed in RadialTimePickerDialog and CalendarDatePickerDialog?
I want to use primary and accent color of my app.

**Comment by nkarasch** [comment]
This was bothering me too. My 1.5.4 fork has a customizable RadialTimePickerDialog and an update to the sample app to show you how to use it. I haven't looked at it yet but I might hit CalendarDatePickerDialog with similar treatment this coming weekend.

**Comment by Rainer-Lang** [comment]
Is it possible to make a pr here?

**Comment by Rainer-Lang** [comment]
Thanks.
Is this also for CalendarDatePickerDialog?

**Comment by nkarasch** [comment]
No, unfortunately.

**Comment by fchauveau** [comment]
Hi @Rainer-Lang 

This feature is avaible since v2.2.0 and #198 have been merged.
