### ISSUE TITLE
Failde to resolve : 'com.doomonafireball.betterpickers:library:1.5.5'

### ISSUE THREAD

**Issue by thomaslc66** [code-troopers/android-betterpickers#151]
When i want to update from 1.5.4 and the errors to 1.5.5 i get this message

**Comment by fchauveau** [comment]
hi @thomaslc66 look's like 1.5.5 is still in snapshot. we are going to release it soon.
Sorry for that.

**Comment by CedricGatay** [comment]
Hi @thomaslc66 as @fchauveau said, 1.5.5 is awaiting its release, if you have the dreaded problem with appcompat, and can use sonatype snapshot repository, you can help us being sure we promote a working version by testing it.

**Comment by fchauveau** [comment]
Hi @thomaslc66 version 1.5.5 has been released. 
This probleme should be fixed

**Comment by thomaslc66** [comment]
Hi thanks for the update, but i take an other library thank you

**Comment by fchauveau** [comment]
Hi @thomaslc66 can you said us which library you used ?
