### ISSUE TITLE
Remove Vibrate Permission

### ISSUE THREAD

**Issue by IcoWeb** [code-troopers/android-betterpickers#161]
Hi, I'm doing an app and using the calendar and number pickers which are both great. 

When my app is ready for release and I install it, it says about VIBRATE permission which I don't want.

I tried to edit the AndroidManifest under the build - intermediates - com.doomonafireball.betterpickers but it gets regenerated again with this perm:
<uses-permission android:name="android.permission.VIBRATE" />

Do you know how I could remove this permission?

**Comment by fchauveau** [comment]
Hi @IcoWeb 
There is a PR #77 that also talk about Vibration permission.
I'll soon look what is the best solution for your problem, It should be fixed for the next release

**Comment by fchauveau** [comment]
Hi @IcoWeb 
this have been fixed via #163 and available in lasts releases
