### ISSUE TITLE
Release 1.6.0

### ISSUE THREAD

**Issue by CedricGatay** [code-troopers/android-betterpickers#164]
As we've included a lot of PR, I think it's time for a new release, I call for a vote to release 1.6.0.
## 

f39b357 Merge pull request #163 from derekbrameyer/feature/Vibration
aff0fd2 remove forced vibration persmission + cherry-pick from PR #77 to check if Vibrate permission is here
792eb58 Update README.md
a9dd908 Update project.properties
108f149 Added project.properties
0cb6f2a Merge pull request #86 from DDRBoxman/MinimumExpirationDate
fe0b7ff Merge pull request #157 from derekbrameyer/update/readme
2a90938 Allow setting a minimum year for the expiration picker.
0a278b9 Merge pull request #152 from nkarasch/master
357c67c changed MyCustomBetterPickersTimePickerDialog to MyCustomBetterPickersRadialTimePickerDialog
c7b66d7 changed BetterPickersTimePickerDialog to BetterPickersRadialTimePickerDialog
e9180a9 add shield.io badges
2b1768f Merge pull request #131 from DreaminginCodeZH/patch-1
4b92d08 Merge pull request #132 from DreaminginCodeZH/patch-2
91a391c Merge pull request #142 from derekbrameyer/feature/setValueOnNumberBuilder
cc826a0 Merge branch 'master' into feature/setValueOnNumberBuilder
8113575 Merge pull request #156 from derekbrameyer/refactor/unusedParams
58911b5 removing sdk and version number from androidManifest file because data are read from gradle files
bf158f4 Merge pull request #155 from derekbrameyer/fix/DateFormatDeprecations
9fbd186 fix removed static char from class android.text.format.DateFormat
8f73a6b Merge pull request #154 from derekbrameyer/update/bumpTargetSDK

**Comment by fchauveau** [comment]
Sounds good to me for 1.6.0

**Comment by bbbenja** [comment]
+1

**Comment by fchauveau** [comment]
Hi, 
just published a snapshot version https://oss.sonatype.org/content/repositories/snapshots/com/doomonafireball/betterpickers/library/1.6.0-SNAPSHOT/

If anyone what to give a try before release.

**Comment by fchauveau** [comment]
uploaded to sonatype and awaiting for publishing : https://oss.sonatype.org/#stagingRepositories

**Comment by fchauveau** [comment]
Done.
