### ISSUE TITLE
EditText.setError(null) must work

### ISSUE THREAD

**Issue by NeverGivinUp** [code-troopers/android-betterpickers#166]
use 
    @Override
    public void setError(CharSequence text) {
        setErrorMessage(text==null?null:text.toString());
        error = errorMessage != null;
    }
instead of 
    @Override
    public void setError(CharSequence text) {
        setErrorMessage(text.toString());
        error = errorMessage != null;
    }

**Comment by fchauveau** [comment]
Hi @NeverGivinUp 

Feel free to make a PR for this, and we will merge it asap.

**Comment by NeverGivinUp** [comment]
Sorry, I posted this bug in the wrong project.
