### ISSUE TITLE
"Done" button in calender dialog is cut

### ISSUE THREAD

**Issue by Danihalf** [code-troopers/android-betterpickers#168]
Hi,

The "Done" button is being cut from the bottom a bit in the calender dialog.
This only happens in Lollipop (api level 21) and only in my personal app. In the sample app I don't see it happening.
Can't find where to configure it, or why it's happening.
Would appreciate some input on it.

![image](https://cloud.githubusercontent.com/assets/11837348/7334655/2b5ddb4a-eba2-11e4-9292-8fa3978b3732.png)

**Comment by fchauveau** [comment]
Hi @Danihalf 
This is the first time I see this happening.

Which other libs are you using in your project ?

**Comment by ilya50515** [comment]
First of all, thank you for your quick reply.
This is the list of libs that i am currently using in my project:

'com.android.support:appcompat-v7:22.+'
'com.google.android.gms:play-services:7.0.0'
'de.hdodenhof:circleimageview:1.2.2'
'com.android.support:recyclerview-v7:22.+'
'com.android.support:cardview-v7:22.+'
'com.squareup.retrofit:retrofit:1.9.0'
'com.squareup.okhttp:okhttp:2.3.0'
'com.squareup.okhttp:okhttp-urlconnection:2.3.0'
'com.google.code.gson:gson:2.3.1'
'com.github.rey5137:material:1.1.0'
'com.github.shell-software:fab:1.0.5'
'de.greenrobot:eventbus:2.4.0'
'com.doomonafireball.betterpickers:library:1.5.5'

**Comment by Danihalf** [comment]
^ working on the same project

**Comment by yurilaguta** [comment]
Most likely this is bonus from 'com.android.support:appcompat-v7:22.+'
have same behaviour here on Nexus 5.

**Comment by robotomeister** [comment]
Same behavior here on a LG G2 running Lollipop. Works fine on all other platforms.

**Comment by siublood** [comment]
Experienced the same problem here. This may be solved by adding the following line before .show()
calendarDatePickerDialog.setStyle(android.R.style.Theme_Holo, android.R.style.Theme_Holo_Light_Dialog);
But the the visual effect of Material Theme is lost. Does any one has a better solution? Thanks!

**Comment by chelexey** [comment]
I have same behavior on Nexus 5 and latest v.1.6.0 with Lollipop.

**Comment by fchauveau** [comment]
HI @chelexey @siublood @robotomeister @Yurii-Laguta 

I just push a snapshot version that must fix this : https://oss.sonatype.org/content/repositories/snapshots/com/code-troopers/betterpickers/library/2.0.3-SNAPSHOT/

To grab it, in you build.gradle just add 

```
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
```

**Comment by CedricGatay** [comment]
@chelexey @siublood @robotomeister @Yurii-Laguta 2.0.3 is now live, could you confirm this is now working as expected?
