### ISSUE TITLE
Gradle doens't build for 1.5.5

### ISSUE THREAD

**Issue by caiob3** [code-troopers/android-betterpickers#170]
Hi, I can't figure why the build fail. This is my Gradle

---

apply plugin: 'android'
apply plugin: 'io.fabric'

repositories {
    maven { url 'https://maven.fabric.io/public' }

```
maven {
    url "http://JRAF.org/static/maven/2"
}
```

}

buildscript {
    repositories {
        mavenCentral()
        maven { url 'https://maven.fabric.io/public' }

```
    maven {
        url "http://JRAF.org/static/maven/2"
    }


}
dependencies {
    classpath 'com.android.tools.build:gradle:1.1.2'
    classpath 'io.fabric.tools:gradle:1.+'
}
```

}

android {

```
compileSdkVersion 22
buildToolsVersion "22.0.1"


defaultConfig {
    applicationId 'com.myapp'
    minSdkVersion 14
    targetSdkVersion 21
    versionCode 100

    versionName "1.0"
}

buildTypes {

    release {
        minifyEnabled false
        proguardFile getDefaultProguardFile('proguard-android.txt')

    }
}
productFlavors {
}
```

}

dependencies {
    compile project(':facebookSDK')
    compile 'com.android.support:support-v4:21.+'
    compile 'com.google.android.gms:play-services:5.0.+'
    compile 'com.viewpagerindicator:library:2.4.1'
    compile ("com.doomonafireball.betterpickers:library:1.5.5")
    compile 'org.jraf:android-switch-backport:1.4.0@aar'
    compile fileTree(dir: 'libs', include: '*.jar')
    compile('com.crashlytics.sdk.android:crashlytics:2.2.2@aar') {
        transitive = true;
    }
}

configurations.all {
    resolutionStrategy {
        force 'com.android.support:support-v4:21.+'
    }
}

---

Any thoughts?

The error says:

Error:(66, 13) Failed to resolve: org.jraf:android-switch-backport:1.4.0

**Comment by fchauveau** [comment]
Hi @caiob3 
First you should start with 

```
apply plugin: 'com.android.application'
```

with is last uptade of android plugin instead of 

```
 apply plugin: 'android'
```

Then let's try some reorder and split your build.gradle in two files, as generated when creating a new project.
And in the first one declare all repo stuffs : 

```
 buildscript {
repositories {
    jcenter()
    maven { url 'https://maven.fabric.io/public' }
}
dependencies {
    classpath 'com.android.tools.build:gradle:1.1.2'
    classpath 'io.fabric.tools:gradle:1.+'
}
 }

 allprojects {
repositories {
    maven { url "http://dl.bintray.com/populov/maven" } // for viewpagerindicator
    jcenter()
    mavenCentral()
    maven { url 'https://maven.fabric.io/public' }
    maven { url "http://JRAF.org/static/maven/2" }
}
 }
```

It should be better

**Comment by caiob3** [comment]
Hi @fchauveau 

Thanks a lot! It worked! I'm not too familiar with Gradle yet but I did exactly what you said and built successfully now :)

Not sure what's the difference though... but it's working now :) You are a rock star! Thanks

Just to leave here, so it can might help others with same/similar issue

On my build.gradle

// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.1.2'
        classpath 'io.fabric.tools:gradle:1.+'
    }
}

allprojects {
    repositories {
        maven { url "http://dl.bintray.com/populov/maven" } // for viewpagerindicator
        jcenter()
        mavenCentral()
        maven { url 'https://maven.fabric.io/public' }
        maven { url "http://JRAF.org/static/maven/2" }
    }
}

and on my app/build.gradle

apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

android {

```
compileSdkVersion 22
buildToolsVersion "22.0.1"



defaultConfig {
    applicationId 'com.myapp'
    minSdkVersion 14
    targetSdkVersion 21
    versionCode 100

    versionName "1.0"
}

buildTypes {

    release {
        minifyEnabled false
        proguardFile getDefaultProguardFile('proguard-android.txt')

    }
}
productFlavors {
}
```

}

dependencies {
    compile project(':facebookSDK')
    compile 'com.android.support:support-v4:21.+'
    compile 'com.google.android.gms:play-services:5.0.+'
    compile 'com.viewpagerindicator:library:2.4.1'
    compile ("com.doomonafireball.betterpickers:library:1.5.5")
    compile 'org.jraf:android-switch-backport:1.4.0@aar'
    compile fileTree(dir: 'libs', include: '*.jar')
    compile('com.crashlytics.sdk.android:crashlytics:2.2.2@aar') {
        transitive = true;
    }
}

configurations.all {
    resolutionStrategy {
        force 'com.android.support:support-v4:21.+'
    }
}
