### ISSUE TITLE
Required only 0-9 digits from NumberPicker dialog? How to remove +/- and . from the code

### ISSUE THREAD

**Issue by hasnahmd** [code-troopers/android-betterpickers#175]
Is there a way to +/- and . from the numberpicker dialog or there any dialog fragment with the positive buttons only

**Comment by fchauveau** [comment]
Hello @mobidroid 

have you tried to use the NumberPickerBuilder#setPlusMinusVisibility method?
Setting this button to INVISBLE will make user able to only input positive numbers.

**Comment by hasnahmd** [comment]
Thanks and how about removing the decimel '.' i need the positive whole numbers only.

**Comment by hasnahmd** [comment]
okay i found out the methods. Thanks bro.

**Comment by fchauveau** [comment]
no problem
