### ISSUE TITLE
Gradle: Failed to resovle

### ISSUE THREAD

**Issue by vijaemanlapaz** [code-troopers/android-betterpickers#180]
I got failed to resolve with gradle
i added the maven url

maven {
    url "http://JRAF.org/static/maven/2"
}

dependencies {
   compile ("com.doomonafireball.betterpickers:library:1.6.0") {
         exclude group: 'com.android.support', module: 'support-v4'
   }
   compile 'org.jraf:android-switch-backport:1.4.0@aar'
}

**Comment by CedricGatay** [comment]
Hi, what is the error trace Gradle gave you ?
Le 5 juil. 2015 6:03 AM, "vijae manlapaz" notifications@github.com a
écrit :
