### ISSUE TITLE
Is there a changelog for version 2.0.0?

### ISSUE THREAD

**Issue by Rainer-Lang** [code-troopers/android-betterpickers#186]

**Comment by fchauveau** [comment]
Hi,
Actually there is no more than the readme for 2.0.0

What information are you missing?
I will try do write changelog soon.

**Comment by fchauveau** [comment]
Hi @Rainer-Lang 
changlog have been updated : https://github.com/derekbrameyer/android-betterpickers/blob/master/Changelog.md

**Comment by Rainer-Lang** [comment]
@fchauveau Thanks a lot! :-)
