### ISSUE TITLE
com.code-troopers.betterpickers  contains a '-' character which is an invalid package name in Java

### ISSUE THREAD

**Issue by blair-anson** [code-troopers/android-betterpickers#188]
I'm attempting to upgrade from 'com.doomonafireball.betterpickers:library:1.5.3' to 'com.code-troopers.betterpickers:library:2.0.0' but I'm getting issues with the Java import statements as they contain an illegal minus character.

I'm using Gradle to add the library to my project.
compile 'com.code-troopers.betterpickers:library:2.0.0'

Can you please change the domain of the package to a valid java package name?

See here for some background info on minus/hyphen characters...

http://stackoverflow.com/questions/27705063/error-importing-java-package-due-to-special-character-in-domain

**Comment by CedricGatay** [comment]
Hi, 

thanks for your feedback, however the package name for the classes are without the hyphen although the Gradle coordinates contains one.

If you try to use the proper imports that are `com.codetroopers.betterpickers` you should not have this problem.

Can you please tell us if it fixes your problem ?

**Comment by blair-anson** [comment]
Ahh, yes that worked. Thanks :-)
