### ISSUE TITLE
Use time picker inside PreferenceFragment

### ISSUE THREAD

**Issue by ido567** [code-troopers/android-betterpickers#192]
There is a way to use the time picker inside a PreferenceFragment?

**Comment by fchauveau** [comment]
Hi @ido567 

Are you using PreferenceFragment support (https://github.com/kolavar/android-support-v4-preferencefragment)?
With that it's easy to use picker using setOnPreferenceClickListener method

**Comment by ido567** [comment]
Great! I didn't know this listener
Thanks a lot
