### ISSUE TITLE
Android M and TimeZone

### ISSUE THREAD

**Issue by jobsolle** [code-troopers/android-betterpickers#195]
mTransitions in Android M TimeZone is changed to a long array. Casting it to int[] will crash.

**Comment by fchauveau** [comment]
Hi @jobsolle 

thx for the notif about that.
I think this PR should fix it https://github.com/code-troopers/android-betterpickers/pull/196

@CedricGatay code review is welcome

**Comment by CedricGatay** [comment]
I have a look at it! Thanks for your work

**Comment by CedricGatay** [comment]
I'm closing as the PR is merged now, should be visible in next release of the library.

**Comment by jobsolle** [comment]
awesome thx
