### ISSUE TITLE
Provide customization option for a title/header of the DatePicker's ViewPagerIndicator

### ISSUE THREAD

**Issue by cavega** [code-troopers/android-betterpickers#20]
Would it be possible to add an option where the ViewPagerIndicator shows a title or label for the current tab.  For someone who has played with the pickers it might be obvious, but to a new user accustomed to the stock Android Date/Time pickers the swiping functionality (i.e. to switch from day, month, year, etc) won't be as discoverable.  By indicating the title (at least for the current tab) it will be more obvious to the user that they can swipe to switch between day/month/year (DatePicker) or hour/minutes (TimePicker).

**Comment by CedricGatay** [comment]
Thanks for your feedback, however this is an old issue, without anything done. I'm closing, reopen it if this is still wished.
