### ISSUE TITLE
Add the ability to remove the switch button on the recurrence picker 

### ISSUE THREAD

**Issue by nellyk** [code-troopers/android-betterpickers#204]
on the recurrence picker , Add the ability to remove the switch button on the recurrence picker

**Comment by fchauveau** [comment]
Hello @nellyk 

We will try to do this as soon as possible

**Comment by nellyk** [comment]
@fchauveau  thank you , do you think if i use getters and setters i can be able to modify this property ?

**Comment by fchauveau** [comment]
Yes we will probably add a setter to toggle this feature

**Comment by nellyk** [comment]
If anyone needs the modified library that has the switch off you can check on this forked repo https://github.com/nellyk/android-betterpickers

**Comment by fchauveau** [comment]
Hey @nellyk you should open a PR with this feature so we will include it in next BetterPickers release

**Comment by Javison** [comment]
Hi,

Could you please specify how to add this improvement or add a PR?

**Comment by fchauveau** [comment]
Hi @nellyk @Javison 

This toogle have been added in release 2.2.2
See sample code for implementation (pass a boolean param to recurrency fragment)

**Comment by nellyk** [comment]
@fchauveau Thank you :-)

**Comment by RowlandOti** [comment]
@nellyk how was this issue resolved?

**Comment by CedricGatay** [comment]
@RowlandOti You need to use the library in its 2.2.2 version. A Boolean extra allows hiding the switch : see https://github.com/code-troopers/android-betterpickers/blob/48dba52861763838a7c8a904a87058e651754d62/sample/src/main/java/com/codetroopers/betterpickers/sample/activity/recurrencepicker/SampleRecurrenceForcedOn.java#L52
