### ISSUE TITLE
Remove annoying warning when compiling

### ISSUE THREAD

**Issue by marcohc** [code-troopers/android-betterpickers#208]
Hi there,

please add these two translations to the default "strings.xml" to remove the warning message:

AGPBI: {"kind":"simple","text":"warning: string \u0027switch_off\u0027 has no default translation.","sources":[{}]}
AGPBI: {"kind":"simple","text":"warning: string \u0027switch_on\u0027 has no default translation.","sources":[{}]}

Thanks for the awesome library :)

**Comment by CedricGatay** [comment]
Thanks, if you have the time to provide a pull request with them it could be great !
