### ISSUE TITLE
String Issues

### ISSUE THREAD

**Issue by nzisis** [code-troopers/android-betterpickers#209]
Hallo guys my name is Nick we are developing an Android app named Pocket-Wallet and we are currently use the old version of BetterPickers by Derek Brameyer. We want to change to your version. Also I noticed that you are not supporting Greek Strings and because we are using Greek Strings it will be great if you add it. Of course we can help you translate the English to Greek. So everyone wins :D

Here is the link of our repository https://github.com/nickstamp93/PocketWallet and you can contract me
to my personal email nzisis93@gmail.com

**Comment by CedricGatay** [comment]
Hi Nick, thanks for the proposal. If you can provide us a Greek translation (through a pull request) we can include it quickly in our next release so your migration could be faster !

Regards

**Comment by nzisis** [comment]
Ok that sounds nice I will discuss it with my partner tomorrow and if everything is ok we are gonna to pull and translate to Greek. I will let you know. Thank for the fast response.

Regards
Nick
