### ISSUE TITLE
Use NumberPickerBuilder to return string

### ISSUE THREAD

**Issue by carmas123** [code-troopers/android-betterpickers#213]
Hi, I need to use NumberPickerBuilder to input a long numeric value (up to 30 chars) that return all chars in string type and not integer or double.
Can I do this?
Have anyone a solution?

for now I handle "onDialogNumberSet" like this:

public void onDialogNumberSet(int reference, int number, double decimal, boolean isNegative, double fullNumber) {

}

but this return a numeric value and not all input chars.

**Comment by fchauveau** [comment]
indeed, numberPicker ignore leading zeros and return result as int values.
So i'm not sure BetterPricker can respond to your current need.

I'll look for a solution to return entered value as string, but i'm not certain do to it in short future

**Comment by fchauveau** [comment]
Hello @carmas123 
As PR #230 have been merged and it new support BigDecimal, support of result as String will not be added.
