### ISSUE TITLE
theming should inherit accent color

### ISSUE THREAD

**Issue by dirkam** [code-troopers/android-betterpickers#218]
Would it be possible to inherit accent color from the app theme?
Switch in the Recurrence Picker Dialog does that. Dialog buttons should inherit that as well, along with the bubbles for the weekbuttons etc.

I tried custom theming but if I set bpTextColor then it will be used for all the text. According to Material Design guidelines in case of dialogs normal text should use the primary text color of the corresponding theme and action buttons should use the accent color.

**Comment by fchauveau** [comment]
Hey @dirkam 

You're right we should look at this.
We will do our best to use correctly primary and accent colors by default.

**Comment by fchauveau** [comment]
Hello @dirkam 

change have been made in last release 2.4.0.
It now use primaryColor as default color for Calendar and Radial pickers.
