### ISSUE TITLE
Calendar renders incorrectly on some tablet devices

### ISSUE THREAD

**Issue by subsymbolic** [code-troopers/android-betterpickers#221]
The calendar is rendered a little off-centre on some tablet devices. In landscape mode the bottom of the calendar is also cut off making it unusable as the buttons cannot be tapped.

Specifically seen on the Nexus 7, 1200x1920px running KitKat (both the device itself and the genymotion emulator). It is however fine on the 800x1200px version.

<img width="1161" alt="landscape" src="https://cloud.githubusercontent.com/assets/1652407/11901575/29764b34-a5a4-11e5-9b07-5644dfe96f05.png">

<img width="786" alt="portrait" src="https://cloud.githubusercontent.com/assets/1652407/11901576/297c0a24-a5a4-11e5-9d06-792adb5f421b.png">

**Comment by fchauveau** [comment]
hello @subsymbolic 
Are you using version 2.2.2 of better-pickers ? Because I did some display fix for tablets in this release.

**Comment by subsymbolic** [comment]
Oh that's exciting, I didn't see the 2.2.2 release, I'm on 2.2.1. I'll try it and let you know if it fixes my issue.

**Comment by subsymbolic** [comment]
@fchauveau version 2.2.2 looks great on all the tablets I tried, thanks :)
I noticed a new issue on smaller devices, I'll raise a separate ticket for that one.

**Comment by fchauveau** [comment]
As it's fixed on 2.2.2, I close this issue
