### ISSUE TITLE
Weekday heading slightly truncated

### ISSUE THREAD

**Issue by subsymbolic** [code-troopers/android-betterpickers#222]
This can be reproduced on:
• Nexus 4, Genymotion emulator, API 19
• Nexus 5, Genymotion emulator, API 21
Thanks for a great project, the calendars looks really slick even on old devices.

<img width="305" alt="nexu4_api19" src="https://cloud.githubusercontent.com/assets/1652407/11912824/da998b04-a646-11e5-8826-0371e6bb3099.png">
<img width="289" alt="nexus_5_api21" src="https://cloud.githubusercontent.com/assets/1652407/11912825/da99e284-a646-11e5-8512-1f9d9c1a1a4d.png">

**Comment by fchauveau** [comment]
Hello @subsymbolic 
Indeed there is a small bug.
It will be fixed in next release.

**Comment by CedricGatay** [comment]
Hi @subsymbolic, this has been fixed on our master branch. It will be included in the next release. 
Thank you for the report !

**Comment by subsymbolic** [comment]
Thanks @CedricGatay, I just picked up the 2.3.0 release. Looks great :)
