### ISSUE TITLE
Truncated year in DatePicker

### ISSUE THREAD

**Issue by deadpixelsociety** [code-troopers/android-betterpickers#224]
Nexus 7 (2012) 1280x800
BP v2.2.2
Lollipop

The DatePicker dialog shows the top of the year truncated on this device:

![Example](http://i.imgur.com/zMPPqOe.png)

**Comment by abdabdulsamad** [comment]
the issue is still there

**Comment by winnerawan** [comment]
issue still there , tested on galaxy a8 2018
