### ISSUE TITLE
CalendarDatePickerDialogFragment object is void (sample code)

### ISSUE THREAD

**Issue by Korpen** [code-troopers/android-betterpickers#239]
It could just be me being incompetent but here is my issue:
I copy-pasted your sample code for basic CalendarDatePicker usage and when I try to call any of the methods of CalendarDatePickerDialogFragment I get an error saying that the variable was of type void instead of CalendarDatePickerDialogFragment.

If I don't call any functions from the DialogFragment I don't get any errors and I can start the app and even bring up the CalendarDatePicker. Since I can't call any of the methods I can't attach a OnDateSetListener which means it doesn't really do anything useful. 

Also, if I don't specify a theme, should the CalendarDatePicker be purple-ish? Or is that another issue I'm having?

Is it just me being incompetent or is this a real issue?

My code: https://gist.github.com/Korpen/da33d6c502bd3e9eed97

**Comment by fchauveau** [comment]
Hello @Korpen,
Good news, you are not incompetent!

I've recently did some change in usage, and actually sample code is not exactly based on same version that last release.

So next release (2.3.0) we be soon available on maven central and upadting your dependence will fix all your problems.

So just wait few hours.
