### ISSUE TITLE
Radial time in not in 12 hours format.

### ISSUE THREAD

**Issue by siddarthsunthankar** [code-troopers/android-betterpickers#241]

**Comment by fchauveau** [comment]
@siddarthsunthankar can you provide a bit more details?

**Comment by siddarthsunthankar** [comment]
As i was using radial time picker for selecting time but it shows the clock in 24 hours format.But i require 12 hour format clock (with Am & Pm displayed below the clock).I saw your sample app which contain 12 hour format clock in radial time picker. so can you help me to implement the same.

**Comment by fchauveau** [comment]
currently you can set this property using   

```
RadialTimePickerDialogFragment#initialize(OnTimeSetListener callback, int hourOfDay, int minute, boolean is24HourMode) {
```

Soon we will provide a new setter only for this purpose

**Comment by siddarthsunthankar** [comment]
Thank you so much for your help.

On Mon, Jan 25, 2016 at 12:36 PM, Florian Chauveau <notifications@github.com

> wrote:
> 
> currently you can set this property using
> 
> RadialTimePickerDialogFragment#initialize(OnTimeSetListener callback, int hourOfDay, int minute, boolean is24HourMode) {
> 
> Soon we will provide a new setter only for this purpose
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/code-troopers/android-betterpickers/issues/241#issuecomment-174421420
> .

## 

_Thanks & Regards_
_Siddarth sunthankar_

**Comment by fchauveau** [comment]
Hello @siddarthsunthankar 
v2.4.0 have been release, you can now force detection on dateFormat using

```
RadialTimePickerDialogFragment.setAutodetectDateFormat(Context);
```
