### ISSUE TITLE
Switch ClassCastException

### ISSUE THREAD

**Issue by melomg** [code-troopers/android-betterpickers#245]
Error at line 711:

java.lang.ClassCastException: android.widget.Switch cannot be cast to android.support.v7.widget.SwitchCompat
                                                                               at com.codetroopers.betterpickers.recurrencepicker.RecurrencePickerDialogFragment
.onCreateView(RecurrencePickerDialogFragment.java:711)

mRepeatSwitch = (SwitchCompat) mView.findViewById(R.id.repeat_switch);
should be cast to Switch

**Comment by fchauveau** [comment]
Hello @melomg 

How can I reproduce this ST? Device and version, 
thank you.

**Comment by melomg** [comment]
Nexus 5 version:6.0.1 it occurs when RecurrencePickerDialogFragment is being created.

**Comment by fchauveau** [comment]
Which version of betterpicker are you using ?

Cast is okay to me as in xml we have a SwichCompat

```
       <android.support.v7.widget.SwitchCompat
                        android:id="@+id/repeat_switch"
                        style="@style/Widget.Holo.Light.CompoundButton.Switch"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="center_vertical"
                        android:layout_marginLeft="4dp" />
```

**Comment by melomg** [comment]
I'm so sorry I guess my other library has a component which has repeat_switch id. Thank you for your interest.
