### ISSUE TITLE
Ability to show a subset of options in Recurrence Picker?

### ISSUE THREAD

**Issue by ashwinprasadmr** [code-troopers/android-betterpickers#247]
Not a issue but a question.

Currently there are options to select  **REPEAT WEEKLY,REPEAT MONTHLY**.. 

Is there a way to limit showing these options based on the requirements?
 For Eg i only need **Repeat Weekly** option, is there any way to hide all other options apart from **Repeat weekly**?

**Comment by fchauveau** [comment]
Hello @ashwinprasadmr 

Currently there is no way to limit recurrence options to only one or two items

**Comment by ashwinprasadmr** [comment]
Thank you for the quick update @fchauveau
