### ISSUE TITLE
Required SDK level

### ISSUE THREAD

**Issue by Seidr** [code-troopers/android-betterpickers#25]
There appears to be no mention of the required SDK level in order for this project to work. When first importing, as I've got the 2.2 SDK downloaded for testing, I assume the project defaulted to that as the SDK, however I needed to change it to a higher SDK level in order to compile.

Perhaps an entry stating the minimum required SDK level would be useful on the main page of this git?

Cheers for the lovely library, very snazzy :)

**Comment by derekbrameyer** [comment]
Thanks! I have updated the README to indicate that, just like ActionBarSherlock, this does require ICS+ at compile time.
