### ISSUE TITLE
RecurrencePickerDialogFragment -Dates not visible 

### ISSUE THREAD

**Issue by llpj** [code-troopers/android-betterpickers#252]
Install sample app from google play, set Recurrence and choose date.

![bp](https://cloud.githubusercontent.com/assets/11827742/12860883/787d91a8-cc85-11e5-9e2d-ccd7549141c3.png)

**Comment by adboco** [comment]
same problem here

**Comment by fchauveau** [comment]
Hi @llpj @adboco 

This will be fixed in next release.

Thanks for reporting.

**Comment by fchauveau** [comment]
version 2.5.1 including fix for this case is now deployed
