### ISSUE TITLE
Upgrade to recent Roboto or convert to Noto?

### ISSUE THREAD

**Issue by 13rac1** [code-troopers/android-betterpickers#258]
The [existing fonts](https://github.com/code-troopers/android-betterpickers/tree/4f32c15fdee8d5f2ba8d7ef84ca1a427c8efa60f/library/src/main/assets/fonts) are quite old:
- `Roboto-Bold.ttf` - Version 1.00000; 2011
- `Roboto-Light.ttf` - Version 1.00000; 2011

Current versions from ASOP are "Version 2.01289; 2015": https://android.googlesource.com/platform/external/roboto-fonts

If still required, they should be upgraded to the recent versions or replaced by Noto (the now recommended font)

Thoughts?

**Comment by fchauveau** [comment]
Thank for reporting, I'll look after that soon

**Comment by fchauveau** [comment]
Updated roboto font.

Will be available in next release
