### ISSUE TITLE
AAPT err(Facade for xxxxx) Not recognizing known sRGB profile

### ISSUE THREAD

**Issue by Jai-GAY** [code-troopers/android-betterpickers#261]
I would like to suggest replacing 4 image files to solve the annoying AAPT error under following library folder. [link attached]
xx\library\src\main\res\drawable-xxhdpi
ic_recurrence_bubble_disabled.png
ic_recurrence_bubble_fill.png
ic_recurrence_bubble_outline.png
ic_recurrence_bubble_outline_disabled.png

AAPT err(Facade for 702391422): C:\app\build\intermediates\exploded-aar\com.code-troopers.betterpickers\library\2.5.1\res\drawable-xxhdpi-v4\ic_recurrence_bubble_outline.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(Facade for 2110892297): C:\app\build\intermediates\exploded-aar\com.code-troopers.betterpickers\library\2.5.1\res\drawable-xxhdpi-v4\ic_recurrence_bubble_disabled.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(Facade for 898291252): C:\app\build\intermediates\exploded-aar\com.code-troopers.betterpickers\library\2.5.1\res\drawable-xxhdpi-v4\ic_recurrence_bubble_outline_disabled.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(Facade for 1904348099): C:\app\build\intermediates\exploded-aar\com.code-troopers.betterpickers\library\2.5.1\res\drawable-xxhdpi-v4\ic_recurrence_bubble_fill.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

<a href="https://www.dropbox.com/" target="_blank">download here with original file name (removed) fixed in 2.5.2</a>

**Comment by fchauveau** [comment]
Thanks @Jai-GAY 

fixed, will be shiped in next release

**Comment by Jai-GAY** [comment]
@fchauveau , really appreciate your good work. thanks to you.
