### ISSUE TITLE
Recureence every X months/years not taken into account on description

### ISSUE THREAD

**Issue by mtrakal** [code-troopers/android-betterpickers#269]
When I set recurrence to: Every X months or Every X years it is not shown in description for X > 1.

Selected: 
Every 3 months on every first Thursday, For 3 events.

Current:
- description is: Monthly (on every Thursday); for 3 times

Expected behaviour:
- Every 3 months (on every Thursday); for 3 times

**Comment by fchauveau** [comment]
Hello @mtrakal 

What description are you talking about ? Can you provide a screenshot ?
Thx

**Comment by mtrakal** [comment]
Sure, it's text presentation of RRULE which is readable for users.

on this screen it is: Monthly; for 5 times, expected: Every 3 months; for 5 times
![device-2016-04-07-135930](https://cloud.githubusercontent.com/assets/1458891/14350363/35957288-fcc9-11e5-96e1-c188dd235e05.png)
![device-2016-04-07-135942](https://cloud.githubusercontent.com/assets/1458891/14350362/359396ac-fcc9-11e5-905b-c2eeb2721c5f.png)

Get `null` when select another variants:
![device-2016-04-07-140300](https://cloud.githubusercontent.com/assets/1458891/14350418/919e1238-fcc9-11e5-97de-a3f4ec38c47b.png)
![device-2016-04-07-140309](https://cloud.githubusercontent.com/assets/1458891/14350417/919bd5e0-fcc9-11e5-869b-e161dc49f4d6.png)

**Comment by CedricGatay** [comment]
This is fixed in #270 that has been merged now, it will be available in next release. I'm closing it, thant you for your report @mtrakal !
