### ISSUE TITLE
Having trouble using BetterPickers with HoloEveryWhere

### ISSUE THREAD

**Issue by JonathanNakhla** [code-troopers/android-betterpickers#27]
Hi there!

I've been having trouble using BetterPickers with HoloEveryWhere. It might just be an issue from my side with setting up both BetterPickers and HoloEveryWhere libraries (I'm new to all this). I'll drop the code I have and the issue I'm getting. Any help would be greatly appreciated! So here's the code: 

``` java
package com.example.myfirstapp;

import org.holoeverywhere.widget.Button;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;

import com.actionbarsherlock.view.Menu;
import com.actionbarsherlock.view.MenuItem;
import com.doomonafireball.betterpickers.timepicker.TimePickerBuilder;
import com.doomonafireball.betterpickers.timepicker.TimePickerDialogFragment;

public class MainActivity extends org.holoeverywhere.app.Activity implements TimePickerDialogFragment.TimePickerDialogHandler{
    private Button theTime;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);


        theTime = (Button) findViewById(R.id.the_button);

        theTime.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                TimePickerBuilder tpb = new TimePickerBuilder()
                        .setFragmentManager(getSupportFragmentManager())
                        .setStyleResId(R.style.BetterPickersDialogFragment);
                tpb.show();
            }
        });
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getSupportMenuInflater().inflate(R.menu.activity_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        Intent showSettings = new Intent(this, SettingsActivity.class);
        startActivity(showSettings);
        return true;
    }

    @Override
    public void onDialogTimeSet(int reference, int hourOfDay, int minute) {
        theTime.setText("" + hourOfDay + ":" + minute);
    }


}
```

And here's the errors I'm getting:

06-16 15:24:24.048: E/AndroidRuntime(25989): FATAL EXCEPTION: main
06-16 15:24:24.048: E/AndroidRuntime(25989): android.view.InflateException: Binary XML file line #7: Error inflating class com.doomonafireball.betterpickers.timepicker.TimePicker
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:376)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:584)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.LayoutInflater.createViewFromTag(LayoutInflater.java:438)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.LayoutInflater.rInflate(LayoutInflater.java:725)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:532)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:482)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:477)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at com.doomonafireball.betterpickers.timepicker.TimePickerDialogFragment.onCreateView(TimePickerDialogFragment.java:87)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at android.support.v4.app.Fragment.performCreateView(Fragment.java:1460)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:911)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1444)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:429)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at android.os.Handler.handleCallback(Handler.java:725)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at android.os.Handler.dispatchMessage(Handler.java:92)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at android.os.Looper.loop(Looper.java:137)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at android.app.ActivityThread.main(ActivityThread.java:5193)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at java.lang.reflect.Method.invokeNative(Native Method)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at java.lang.reflect.Method.invoke(Method.java:511)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:101)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at dalvik.system.NativeStart.main(Native Method)
06-16 15:24:24.048: E/AndroidRuntime(25989): Caused by: java.lang.reflect.InvocationTargetException
06-16 15:24:24.048: E/AndroidRuntime(25989):    at java.lang.reflect.Constructor.constructNative(Native Method)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:352)
06-16 15:24:24.048: E/AndroidRuntime(25989):    ... 23 more
06-16 15:24:24.048: E/AndroidRuntime(25989): Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class <unknown>
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:376)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:588)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.LayoutInflater.createViewFromTag(LayoutInflater.java:438)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.LayoutInflater.rInflate(LayoutInflater.java:725)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.LayoutInflater.parseInclude(LayoutInflater.java:641)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.LayoutInflater.rInflate(LayoutInflater.java:715)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:532)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:482)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:477)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at com.doomonafireball.betterpickers.timepicker.TimePicker.<init>(TimePicker.java:70)
06-16 15:24:24.048: E/AndroidRuntime(25989):    ... 26 more
06-16 15:24:24.048: E/AndroidRuntime(25989): Caused by: java.lang.reflect.InvocationTargetException
06-16 15:24:24.048: E/AndroidRuntime(25989):    at java.lang.reflect.Constructor.constructNative(Native Method)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:352)
06-16 15:24:24.048: E/AndroidRuntime(25989):    ... 35 more
06-16 15:24:24.048: E/AndroidRuntime(25989): Caused by: java.lang.IllegalStateException: Could not find font in raw resources: roboto_light
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.FontLoader$RawLazyFont.loadTypeface(FontLoader.java:187)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.FontLoader$Font.getTypeface(FontLoader.java:52)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.FontLoader$FontCollector.getTypeface(FontLoader.java:81)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.FontLoader.applyInternal(FontLoader.java:296)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.FontLoader.apply(FontLoader.java:273)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.FontLoader.applyDefaultFont(FontLoader.java:278)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.widget.TextView.setFontStyle(TextView.java:109)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.widget.Button.setFontStyle(Button.java:38)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.widget.TextView.setTextAppearance(TextView.java:151)
06-16 15:24:24.048: E/AndroidRuntime(25989):    at org.holoeverywhere.
06-16 15:24:26.056: I/Process(25989): Sending signal. PID: 25989 SIG: 9

**Comment by brmcmaho** [comment]
It's failing to find the roboto_light font in the resources. Did you copy the betterpickers assets folder into your project?

**Comment by bbbenja** [comment]
This issue is very old now, I close it and feel free to reopen it if you still have this problem
