### ISSUE TITLE
When picking date, it picks the wrong month

### ISSUE THREAD

**Issue by aferrerb** [code-troopers/android-betterpickers#271]
Hello, I have an issue which is to do with the month when picking a date.
so when I look into the date chosen in the function
public void onDateSet(CalendarDatePickerDialogFragment dialog, int year, int monthOfYear, int dayOfMonth)

And I pick the 20th of April, it tells me it is the 20th of March ... Would you know what I am doing wrong?
Thanks

**Comment by CedricGatay** [comment]
Hi @aferrerb, in fact in Java months are starting at index 0, I think this is what confuses you.

**Comment by aferrerb** [comment]
Ah!! That makes sense ... apologies for the ignorance ... Thanks a lot.
