### ISSUE TITLE
CalendarDatePickerDialogFragment.setDisabledDays

### ISSUE THREAD

**Issue by anismarzouk** [code-troopers/android-betterpickers#275]
How can we use setDisabledDays for disabling the weekends in the calender ??

**Comment by fchauveau** [comment]
Hello @anismarzouk 

Actually there is nothing for doing that.
But if you put limit min and max dates on calendar, then it will be easy to manually find all weekend days between those dates for passing them to calendar as DisabledDays.

**Comment by ghost** [comment]
@anismarzouk The SampleCalendarDateRangeAndDisabledDays.java example that I added actually shows how you can add weekend days as disabled days.
