### ISSUE TITLE
CalendarDatePickerDialogFragment not showing day of week header on api 22

### ISSUE THREAD

**Issue by ionutbarau** [code-troopers/android-betterpickers#276]
I have tested in api 21 and it works as expected. However on api 22 the day of week header is missing on CalendarDatePickerDialogFragment.

**Comment by fchauveau** [comment]
Hello @ionutbarau 

Can you provide a screenshot and give me the phone name and version you used ?
Thx

**Comment by ionutbarau** [comment]
Hi @fchauveau 

The phone is a Lenovo A2010-a with Android version 5.1.

This is the screen shoot
![screenshot_2016-05-04-23-54-51](https://cloud.githubusercontent.com/assets/15799262/15028981/28a754c4-1254-11e6-9abc-93d720fdd910.png)

Thanks

**Comment by fchauveau** [comment]
Okay, so it's not a bug, it's a feature :D
On small screen devices, header is not shown in order to keep enough for other components.
