### ISSUE TITLE
Dont found documentation for use picker 

### ISSUE THREAD

**Issue by mealbarracin10** [code-troopers/android-betterpickers#288]
how to get the time after the picker you click on the button ok, thanks for your help

**Comment by fchauveau** [comment]
Hey @MartinAlbarracin 

For all pickers you have a class to implements in your activity or fragment to get call back after user pick value.
To get all details, have a look at samples https://github.com/code-troopers/android-betterpickers/tree/master/sample/src/main/java/com/codetroopers/betterpickers/sample/activity
