### ISSUE TITLE
Miss typed code

### ISSUE THREAD

**Issue by richard-muvirimi** [code-troopers/android-betterpickers#290]
android-betterpickers/library/src/main/java/com/codetroopers/betterpickers/recurrencepicker/EventRecurrence.java on line 373 

appendNumbers(s, ";BYSECOND=", this.byhourCount, this.byhour);

instead of 

appendNumbers(s, ";BYHOUR=", this.byhourCount, this.byhour);

**Comment by fchauveau** [comment]
Thank you.
Fixed, will be published in next release.

**Comment by fchauveau** [comment]
@tygalive  fixed in release 2.5.6
