### ISSUE TITLE
Date with range and before/after range color

### ISSUE THREAD

**Issue by mtrakal** [code-troopers/android-betterpickers#294]
When I want to use code as in sample `SampleCalendarDateRange` there is no visualize possible range of days.

I didn't set any disabled days (they are before and after range, not inside), days have same text color. It would be nice when days before/after range could be by default lighter.

As you can see in sample, I select last possible selected day in range, but I can't visually see that it is last possible day.

![device-2016-05-25-135342](https://cloud.githubusercontent.com/assets/1458891/15539008/1ef2ff96-2280-11e6-874a-766f471efc67.png)

**Comment by fchauveau** [comment]
Indeed we must apply a special color theme on not available days

**Comment by fchauveau** [comment]
Fixed in v3 currently releasing
