### ISSUE TITLE
Removing strip from top of dialog

### ISSUE THREAD

**Issue by bridgeri127** [code-troopers/android-betterpickers#295]
I have a problem with styling the dialog fragment as I cannot work out how to remove the stripe of color from the top of the radial time picker dialog. Could anyone suggest how to go about this? I have tried binding the view with id time_picker_dialog and replacing its layout params, but to no avail.

The green part of this screenshot should be flush against the top of the dialog.

![screen shot 2016-05-30 at 13 05 03](https://cloud.githubusercontent.com/assets/9522610/15649140/24dd9d5e-2667-11e6-9c57-15c3a0653233.png)

**Comment by fchauveau** [comment]
hey @bridgeri127 
this must heve been fixed in release 2.5.6
