### ISSUE TITLE
Radial Time Picker selected value contrasting color

### ISSUE THREAD

**Issue by bridgeri127** [code-troopers/android-betterpickers#301]
Hi

I have been using your library recently and needed to be able to set the selected value to be drawn in a contrasting color. I forked the repo and successfully implemented this and I was wondering would you welcome a PR to merge this back in your library?

**Comment by fchauveau** [comment]
Hello @bridgeri127 

I'm working on a update for customization that will be release soon (v3.0.0)
So I would be better to wait after that to see if a PR is still needed.

Thanks for asking. I'll notify you.

**Comment by fchauveau** [comment]
Update about style have been done in v3 currently releasing
