### ISSUE TITLE
CalendarDatePicker not showing all days in a month

### ISSUE THREAD

**Issue by alensiljak** [code-troopers/android-betterpickers#302]
For months that spread over more than 5 rows, not all the days are visible. This happens if a month has 31 days and it starts on Saturday or Sunday. The last day(s) are not visible and the calendar needs to be scrolled, which is not intuitive for most of our users, unfortunately.

Example: October 31st, 2016

<img src="https://cloud.githubusercontent.com/assets/462445/15958822/11364ece-2ef8-11e6-8176-4313edea62de.png" width="200px" />

However, this happens only on some devices. In an emulator, the top part is smaller and the whole calendar is visible. On Samsung Galaxy A5 2016 I get the above. Other users also reported the same.

<img src="https://cloud.githubusercontent.com/assets/462445/15958894/62c41668-2ef8-11e6-93df-f3b09e0178af.png" width="200px" />

Thanks for the great set of pickers!

**Comment by fchauveau** [comment]
Hello @MisterY 
Difference between smaller and bigger calendar is made on device screen size, that explain why on some device there is full header.

For display of all days of month, as the view is scrollable we don't consider this as an issue.
So we will not change this for the moment.
Thx.
