### ISSUE TITLE
How to initialize CalendarDatePickerDialogFragment to start in year view?

### ISSUE THREAD

**Issue by Jockay** [code-troopers/android-betterpickers#303]
Is there a solution to start a CalendarDatePickerDialogFragment dialog in year view?
The closest thing I found is the setCurrentView(viewIndex : int) : void method, but its private.

**Comment by fchauveau** [comment]
Hello @Jockay 

No there is no way for the moment to display year by default.
Fell free to make a PR for that.

**Comment by wrozwad** [comment]
+1
