### ISSUE TITLE
Can I  get the dates of a range between two dates

### ISSUE THREAD

**Issue by MichaelJokAr** [code-troopers/android-betterpickers#312]
I want to get the dates  of a range between two dates;It's has this feature？

**Comment by MichaelJokAr** [comment]
like this:
![qq20160719-0 2x](https://cloud.githubusercontent.com/assets/8246218/16942474/c78d0e6c-4dc8-11e6-9d9d-27358e3ae55f.png)

**Comment by fchauveau** [comment]
@a1018875550 This kind of feature is not available and its really not planned to dev it.
