### ISSUE TITLE
Leading Zero in Date Picker

### ISSUE THREAD

**Issue by dripfeedmedical** [code-troopers/android-betterpickers#316]
We've noticed that in the text-based datePicker it's slightly counter-intuitive from a UX point of view to have to press the 'tick' icon to move on from a date beginning with 1, 2, or 3. The zero button is deactivated as a default.

Has anyone come across a way of allowing dates in the 01, 02, 03 date format to be allowed, with automatic progression to the month field?

**Comment by fchauveau** [comment]
Hello @dripfeedmedical 

can you provide a screenshot of what you talk about, cause i'm not sure to understanding correctly.
And in which language do you have this behavior ?

thx
