### ISSUE TITLE
Setting up a Gradle build

### ISSUE THREAD

**Issue by robpvn** [code-troopers/android-betterpickers#32]
It would be great if this project had a gradle build and published .aar packages, since that is where Android develoment is headed now. I believe this issue depends on  JakeWharton/Android-ViewPagerIndicator#229 (or the duplicate issue 241) being merged, since you depend on that library.

**Comment by intrications** [comment]
A temporary solution is to use the maven repo at https://github.com/Goddchen/mvn-repo

**Comment by Gawdl3y** [comment]
Here's a good guide for publishing an .aar to Maven Central: http://www.vandalsoftware.com/post/52468430435/publishing-an-android-library-aar-to-a-maven

**Comment by simonbengtsson** [comment]
Unfortunately the above mentioned repo (when this written at least) only has support for version 1.3.1 of Android Better Pickers. If someone want to use this library with Android Studio, here is how I got it working http://stackoverflow.com/questions/21233687/add-android-better-pickers-as-a-gradle-dependency

**Comment by derekbrameyer** [comment]
This has _finally_ been resolved, thanks to some work on the Android Maven Plugin.  BetterPickers is now packaged as an .aar and is in Maven Central!

**Comment by ciceromsjr** [comment]
Hi!

I'm using your library (is great), but I'm having this error when calling the dialog: 

java.lang.NoClassDefFoundError: com.doomonafireball.betterpickers.numberpicker.NumberPickerBuilder

Moreover, Intelli J recognizes your library as a new module to be executed.
