### ISSUE TITLE
Return wrong month in CalendarDatePickerDialogFragment

### ISSUE THREAD

**Issue by sagarchavda** [code-troopers/android-betterpickers#324]
When i select 2016-09-14 it was return 2016-08-14. In a month it's return -1 month. There are it's a bug i think.

**Comment by fchauveau** [comment]
Hello @sam4444 

In java, value for month number start a 0, so that"s why you may think there is an issue. But everything works correctly.

**Comment by aryayudha** [comment]
i have same issue. How to fix it?

**Comment by fchauveau** [comment]
Hi,

its not an issue, java manage month numbers from 0 to 11
