### ISSUE TITLE
When user Click Cancel button

### ISSUE THREAD

**Issue by MahmoudAlnouno** [code-troopers/android-betterpickers#326]
how I can get event when user click button cancel 

```
CalendarDatePickerDialogFragment cdp = new CalendarDatePickerDialogFragment()
                .setOnDateSetListener(TaskFragment.this).setOnDismissListener(this)
                .setPreselectedDate(calendar.get(Calendar.YEAR), calendar.get(Calendar.MONTH), calendar.get(Calendar.DAY_OF_MONTH))
                .setDoneText(getString(R.string.okText))
                .setCancelText(getString(R.string.cancel));
```

**Comment by fchauveau** [comment]
released in version 3.1.0

**Comment by yincrash** [comment]
Unfortunately, `onDismiss()` is called for both the done and cancel actions. Did you mean to implement a cancel listener? `onDismiss()` is still useful when catching back button presses though.

**Comment by yincrash** [comment]
Oh, it looks like the underlying dialog's cancel is never called when the cancel button is pressed, so essentially in the `onDismiss()` listener, we have to check whether whatever picker's `on*Set()` was called first.
