### ISSUE TITLE
Translation problem

### ISSUE THREAD

**Issue by JoduWei** [code-troopers/android-betterpickers#330]
Hi.
I like the DatePicker very much, but there is one translation issue with the German Translation.
The month "März" is shown as "MARZ" and there is not enough space left fort the year.
I would suggest you, to use an abbreviation. Maybe "MRZ" the user will know what you mean.

![screenshot_1478477695](https://cloud.githubusercontent.com/assets/23301345/20043134/d6dfd0d2-a487-11e6-8164-a03086756abb.png)
![screenshot_1478477708](https://cloud.githubusercontent.com/assets/23301345/20043135/d6e129aa-a487-11e6-984a-73482d9f6a40.png)

**Comment by fchauveau** [comment]
Hello @JeDuWei 

We are aware of issue about year sometimes truncated. We still look for a good solution.
But we will include translation change for MRZ in next release
