### ISSUE TITLE
min_time_error Display

### ISSUE THREAD

**Issue by squeeish** [code-troopers/android-betterpickers#333]
![image](https://cloud.githubusercontent.com/assets/3531468/20524025/2a821994-b0f3-11e6-963e-37a421a5e4d5.png)

min_time_error message is cut off. Does anyone know why this happens? The sample is working fine though.

Also, is there a way to customize this message?

**Comment by fchauveau** [comment]
Hello @squeeish 

I've already see that once, what is your device an android version?
For customization its not yet possible.

**Comment by squeeish** [comment]
Hi @fchauveau : Nexus 5 running Android 6.0.1, stock. The weird thing is the sample works correctly (downloaded from play store). Does setting `ThemeCustom` have anything to do with it?

Here's how I'm implementing it:

`new RadialTimePickerDialogFragment()`
`.setOnTimeSetListener(SearchFragment.this)`
`.setPastMinutesLimit(0)`
`.setValidateDateTime(Calendar.getInstance())`
`.setThemeCustom(R.style.MyPickerStyle)`
`.setDoneText(getString(R.string.button_ok))`
`.setCancelText(getString(R.string.button_cancel))`
`.setPickerDate(currentDateTimeCal)`
`.show(getChildFragmentManager(), "");`

**Comment by fchauveau** [comment]
oh, I think you found the issue, sample on play store is probably few versions late.
So it mean it's a regression.

I don't have many time right now, can you try with importing older release and see if behaviour is better ?

**Comment by squeeish** [comment]
@fchauveau I tried down to 2.5.6, all of them have the same cut off text.

Then I disabled Calligraphy (custom font, https://github.com/chrisjenx/Calligraphy) and ran it with v3.0.1, and now it displays properly.

I'll find a workaround for this. Thank you!

**Comment by fchauveau** [comment]
Okay Thx.
Please repport here the solution you will use. It can help other people.
