### ISSUE TITLE
Noob question...but how to use? (doesn't import)

### ISSUE THREAD

**Issue by evanrich** [code-troopers/android-betterpickers#39]
I tried following the directions, which congrats, are simple enough, but for some reason this doesn't import right.   I added it to my workspace in Eclipse by doing the usual (File->Import->Existing Code...) just like I did for actionbarsherlock.  It showed 1059 errors.   I tried changing the target API to 4.0. as instructions said, this dropped it down to 1015 errors, but still doesn't work.  I lastly tried adding actionbarsherlock library to this as a library, and that dropped it down to 644 errors but still can't get it to work.   FWIW, I'm using Kepler and not android studio.  I've imported projects before so not sure why this isn't working. :(

Do I need to also get NineOldAndroids?

Help?

Edit:  It seems like I fixed it...required to add external Jar nineoldandroids, an adding actionbarsherlock as a required library to this library

**Comment by derekbrameyer** [comment]
Make sure you have included the fonts in the assets/ folder of your
project. Take a look at the demos project for more information.
