### ISSUE TITLE
NoSuchMethodError under Api Level < 10

### ISSUE THREAD

**Issue by MOST2K2** [code-troopers/android-betterpickers#44]
http://developer.android.com/reference/java/util/Calendar.html#getDisplayName%28int,%20int,%20java.util.Locale%29

Error occurred in method:
com.doomonafireball.betterpickers.calendardatepicker.CalendarDatePickerDialog.updateDisplay(boolean)

Please fix it.

Great LIB!

Regards

**Comment by shaunidiot** [comment]
The README.MD file specify this is for Android 4.0 (API 14.0)  and above.
EDIT : Sample minSDK is 10. I doubt it's for projects with API < 10. Method is for API > 9.
What's your project minSDK?

**Comment by intrications** [comment]
@shaunidiot The Readme says "your project must be compiled with Android 4.0 (API level 14) or newer". This is not the same as having a minSdk of 14.

I'm not sure what the minimum version is though because the AndroidManifest.xml of the library says minSdk = 4.

**Comment by CedricGatay** [comment]
We need to check if this is still relevant.

**Comment by CedricGatay** [comment]
Can't reproduce, closing.
