### ISSUE TITLE
Support library dependency not resolvable via Maven Central

### ISSUE THREAD

**Issue by schildbach** [code-troopers/android-betterpickers#45]
When compiling from master:

Could not resolve dependencies for project com.doomonafireball.betterpickers:library:apklib:1.4.3-SNAPSHOT: Failure to find com.google.android:support-v4:jar:18

The last version of support-v4 on Maven Central is "r7". It would be nice if betterpickers would depend only on artifacts that can be resolved via Maven Central. (This is also a requirement for uploading it to Maven Central afaik.)

**Comment by ashokcs** [comment]
Same issue as above..   please give us solution

**Comment by graham-huck** [comment]
Agreed.  Really frustrating to get this implemented into a project because of it.

**Comment by derekbrameyer** [comment]
I will get to work on this issue soon.  Not sure if I explicitly _need_ version 18 of the jar for some reason or another.

In the meantime, I strongly suggest looking in to the Maven Android SDK Deployer to resolve issues now: https://github.com/mosabua/maven-android-sdk-deployer

Sure, the latest Maven Central version of support-v4 is r7, but even the latest version of Android itself is only 4.1.1.4.  The SDK deployer solves this and allows for usage of more recent versions of Android and the support library.

**Comment by schildbach** [comment]
The maven-android-sdk-deployer is not the right way to solve this imho. Artifacts on Maven Central are meant to be able to be build just using dependencies from Maven Central.

The right way would be to work on getting recent Android versions into Maven Central. Then recent support library version should go into Maven Central (I can volunteer for this part -- did this before). Finally, betterpickers can go in with the right dependencies.

**Comment by derekbrameyer** [comment]
Given that Google has seemingly dropped support for Maven dependencies and uploading them to Maven Central, I'm not sure how "we" (the Android dev community) can get the artifacts up there.  You say you've uploaded the support library before?  I was always under the impression that someone from the official Google team would need to do something like that.

**Comment by schildbach** [comment]
No, the artifacts on Maven Central are not uploaded by Google.

**Comment by kelchm** [comment]
Stupid question: why can't com.android.support:support-v4 be used instead of com.google.android:support-v4?

My understanding is that com.google.android:support-v4 is provided by Google while  com.google.android:support-v4 is not.

Edit: okay, after digging into this further I'm guessing that com.android.support:support-v4 isn't on maven central, it's on Google's own repository (via the android-library plugin?).  Still, surely there is some way to work around this.

**Comment by derekbrameyer** [comment]
The library now depends on com.android.support and is packaged as an .aar.

I tested this with a standalong Gradle project and was able to compile it fine, though I needed to add an exclusion if using the support library.

**Comment by schildbach** [comment]
Great! Thanks for your work on this.
