### ISSUE TITLE
Orientation issue that you haven't handled.

### ISSUE THREAD

**Issue by ashokcs** [code-troopers/android-betterpickers#47]
Hi here is one serious issue in your app.  

It is easily reproducible from ur sample app.
1.Click the set button.  The date picker dialog appears.
2. Change the orientation.
3.Tap any date and "done".

When all the above three steps over, you cannot see the date as be set.

please guide me to handle this issue soon..

**Comment by CedricGatay** [comment]
Seems to have been resolved now, closing
