### ISSUE TITLE
Change Default Android theme in pickers

### ISSUE THREAD

**Issue by tausiq** [code-troopers/android-betterpickers#48]
Could you add an easy to setup option to change the default picker theme. 

Currently I have a project that is using Holo Dark Android theme and the picker is look like below, 

![device-2013-12-02-182227](https://f.cloud.github.com/assets/2399257/1654484/78e0b202-5b4d-11e3-9d9f-006c9c24fe12.png)

I guess its taking Holo Dark theme from the context 
I would like it to look like the following 

![device-2013-12-02-172140](https://f.cloud.github.com/assets/2399257/1654488/8b2dbca2-5b4d-11e3-97bf-e371abf169a1.png)

**Comment by fchauveau** [comment]
Hello @tausiq 

Long long time after... this is now available. you can see PR #198 
Its in release since 2.2.0
