### ISSUE TITLE
Font issue in TimePicker

### ISSUE THREAD

**Issue by inteist** [code-troopers/android-betterpickers#54]
Not sure what was fixed in the 1.4 
(Fix for Android 4.3 font rendering)

but still having issues on Android 4.4.2

![screenshot_2014-01-09-16-13-17](https://f.cloud.github.com/assets/53954/1882919/67cb898a-797d-11e3-826f-bedde36d5adb.png)

**Comment by derekbrameyer** [comment]
This is resolved in the 1.5.2 release.

**Comment by Den-Rimus** [comment]
This is not resolved in 1.5.2
On Galaxy S2 this reproduces (screen qualifies as normal, 4.1.2), on HTC One X (big screen), Nexus 4 (big screen), and 2.3.7 genymotion with 540*960 - NOT reproduced.

I tried to look into lib, but didn't manage to understand those padding ratios in ZeroTopPaddingView...

![betterpicker_of_bounds](https://cloud.githubusercontent.com/assets/3531046/3689898/20af35ea-1344-11e4-9a5d-a4071a2be0ea.png)
