### ISSUE TITLE
NullPointerException in RadialTimePickerDialog fragment

### ISSUE THREAD

**Issue by arichiardi** [code-troopers/android-betterpickers#57]
The Fragment crashes when embedded in a frame instead of being used as Dialog (not, Android specs allows this usage).

Instanciating...

```
DialogFragment newFragment = RadialTimePickerDialog.newInstance(new OnTimeSetListener() {...}
```

...and then launching it (first branch in case of landscape orientation):

```
if (hasDialogFrame) {
       FragmentTransaction ft = getSupportFragmentManager().beginTransaction();
       ft.add(R.id.main_dialogs, fragment, fragment.getTag())
         .setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE)
          .commit();
} else {
      ...
}
```

Return an NPE in `RadialTimePickerDialog.java`:

```
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
            Bundle savedInstanceState) {
        getDialog().getWindow().requestFeature(Window.FEATURE_NO_TITLE);
```

Because the Dialog is never created (`DialogFragment.java`):

```
@Override
public LayoutInflater getLayoutInflater(Bundle savedInstanceState) {
    if (!mShowsDialog) {
        return super.getLayoutInflater(savedInstanceState);
    }
```

Can you confirm the issue? A solution would be to remove the request in the onCreateView (that is the only method gets called in this case by the Android framework...
Thanks!

**Comment by gerosprime** [comment]
onCreateView() of DialogFragment is called first before onCreateDialog() that's why getDialog() returns null

**Comment by arichiardi** [comment]
Not sure about that...I think this class needs some refactoring (I tried it as normal dialog, it works smoothly and it's very nice...), because doesn't comply with the Fragment protocol.

In case of embedded fragment, only onCreateView is called, but the class relies on:

```
public Dialog onCreateDialog(Bundle savedInstanceState) {
    return new Dialog(getActivity(), getTheme());
}
```

in DialogFrament.java, which creates the Dialog. The dialog is never created in this case. I will fork and provide a patch, it should be easy to workaround, unless someone is already working on it...
