### ISSUE TITLE
HMSPicker InflationException

### ISSUE THREAD

**Issue by liusiqi43** [code-troopers/android-betterpickers#59]
Hello, 

I've tried to use hmsPicker in a android.support.v4.app.FragmentActivity and I used the same code as in your sample app. 

``` java
btnDuration.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                HmsPickerBuilder hpb = new HmsPickerBuilder()
                        .setFragmentManager(getSupportFragmentManager())
                        .setStyleResId(R.style.BetterPickersDialogFragment_Light);
                hpb.show();
            }
        });
```

However, it produce an error as below when clicked, is this normal? I've tested against 4.3 and 4.4. Could you please take a look at it? Thanks! 

> 02-03 00:32:52.934: E/AndroidRuntime(4690): android.view.InflateException: Binary XML file line #7: Error inflating class com.doomonafireball.betterpickers.hmspicker.HmsPicker
> 02-03 00:32:52.934: E/AndroidRuntime(4690):     at android.view.LayoutInflater.createView(LayoutInflater.java:620)
> 02-03 00:32:52.934: E/AndroidRuntime(4690):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
> 02-03 00:32:52.934: E/AndroidRuntime(4690):     at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
> 02-03 00:32:52.934: E/AndroidRuntime(4690):     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
> 02-03 00:32:52.934: E/AndroidRuntime(4690):     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
> 02-03 00:32:52.934: E/AndroidRuntime(4690):     at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
> 02-03 00:32:52.934: E/AndroidRuntime(4690):     at com.doomonafireball.betterpickers.hmspicker.HmsPickerDialogFragment.onCreateView(HmsPickerDialogFragment.java:96)

**Comment by drupalmav** [comment]
any luck with this? I am getting the same issue

**Comment by CedricGatay** [comment]
Can you provide a sample project to allow us to understand what is going on ? @drupalmav @liusiqi43
