### ISSUE TITLE
Numbers are cut in 7" landscape layout

### ISSUE THREAD

**Issue by spacecowboy** [code-troopers/android-betterpickers#6]
Noticed this in the sample app on my Nexus7 in landscape orientation:

![Imgur](http://i.imgur.com/RmRLVjf.png)

**Comment by derekbrameyer** [comment]
Thanks for noticing! Just fixed this.  The issue is that the DatePicker is using a ViewPager for the keyboards, and as such needs to have a defined height.

**Comment by spacecowboy** [comment]
Superb!
