### ISSUE TITLE
Wrong dependencies everywhere..

### ISSUE THREAD

**Issue by ghost** [code-troopers/android-betterpickers#61]
I don't know what the hack is going on but it's not possible to import your projects (sample + lib) into Eclipse. I mean - it's possible to import them, but they have tons of wrong dependencies.

Am I doing something wrong?

Importing the project as usual and adding it as a lib to another project.. I'd love to use your lib - it looks fabulous - but it really sucks that it can't be included as a normal lib.

**Comment by CedricGatay** [comment]
Closing
