### ISSUE TITLE
Reducing APK size by only including desired pickers?

### ISSUE THREAD

**Issue by coreyog** [code-troopers/android-betterpickers#65]
My project only calls for the Radial Time Picker Dialog. How can I reduce the library to only the necessary pieces?

**Comment by ironjan** [comment]
You could fork this library and remove the unneeded things. if you add this repository as remote site you can also get updates ;)

**Comment by alana-mullen** [comment]
You could use Proguard which would remove the unused code in the release version of your app.

**Comment by derekbrameyer** [comment]
Proguard would be the way to go here.  You could also do a fork or just use the relevant files, but it can get tedious to maintain after a while.
