### ISSUE TITLE
TimePicker closing on android 2.3.3

### ISSUE THREAD

**Issue by arturgaleno** [code-troopers/android-betterpickers#69]
Hi,

I'm trying use better pickers 1.5.2, time picker on android 2.3.3. But dialog don't float on screen. All the app closes but i don't have any stacktrace (o.o).

I get the source code and all classes of date picker are importing support v4.

Anyone can help me?

**Comment by plastiv** [comment]
Same behavior on 4.0.3 for NumberPickerDialog. I believe some of the Jellybean api used, which is missing on previous platforms.

**Comment by arturgaleno** [comment]
It's strange because they use FragmentDialog, but i tested inflate an FragmentDialog, and the fragment inflate was succesfull using support v4. So this is not a problem in FragmentDialog it self, i think this is some issue with better picks.

Some Jedi to help us??

**Comment by CedricGatay** [comment]
@arturgaleno @plastiv did you managed to understand what was going on ?

**Comment by arturgaleno** [comment]
Is was more than one year ago. I changed my UI, so I don't need use that library any more =/
