### ISSUE TITLE
Fonts are not in library

### ISSUE THREAD

**Issue by spacecowboy** [code-troopers/android-betterpickers#7]
The library project is missing the asset folder. They are in the sample project instead.

Gives rise to nice errors like this :)

E/AndroidRuntime(25996): Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class com.doomonafireball.betterpickers.timepicker.TimerView
E/AndroidRuntime(25996):    at android.view.LayoutInflater.createView(LayoutInflater.java:613)
E/AndroidRuntime(25996):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
E/AndroidRuntime(25996):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
E/AndroidRuntime(25996):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
E/AndroidRuntime(25996):    at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
E/AndroidRuntime(25996):    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
E/AndroidRuntime(25996):    at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
E/AndroidRuntime(25996):    at com.doomonafireball.betterpickers.timepicker.TimePicker.<init>(TimePicker.java:70)
E/AndroidRuntime(25996):    ... 24 more
E/AndroidRuntime(25996): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(25996):    at java.lang.reflect.Constructor.constructNative(Native Method)
E/AndroidRuntime(25996):    at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
E/AndroidRuntime(25996):    at android.view.LayoutInflater.createView(LayoutInflater.java:587)
E/AndroidRuntime(25996):    ... 31 more
E/AndroidRuntime(25996): Caused by: java.lang.RuntimeException: native typeface cannot be made
E/AndroidRuntime(25996):    at android.graphics.Typeface.<init>(Typeface.java:175)
E/AndroidRuntime(25996):    at android.graphics.Typeface.createFromAsset(Typeface.java:149)
E/AndroidRuntime(25996):    at com.doomonafireball.betterpickers.timepicker.TimerView.<init>(TimerView.java:31)
E/AndroidRuntime(25996):    ... 34 more

**Comment by derekbrameyer** [comment]
Yup, unfortunately that's just a platform limitation at the moment.  You can package them into your app's assets/fonts folder (or create one if it doesn't have one right now) and it'll work correctly.

I may explore adding the fonts to res/raw and doing decoding there, but that would make the library a bit bloated.

Some relevant discussion here: http://stackoverflow.com/questions/6346889/how-to-reference-an-asset-in-a-library-project

**Comment by spacecowboy** [comment]
Thanks for the quick reply. Just after posting this I noticed that copying them into the library's asset folder did not alleviate the issue. Moving them into my own app's asset folder worked nicely.
