### ISSUE TITLE
Crash on monthly recurrence

### ISSUE THREAD

**Issue by dgtale** [code-troopers/android-betterpickers#80]
How to reproduce the issue:
1. Choose repeat "Monthly"
2. Select the second radio button, eg: on every fourth Friday
3. Press "Done"
-> crash

**Comment by lucasarcouto** [comment]
I was able to fix this. It's rather a misusage than a bug on the library.
On the callback listener onRecurrenceSet(String rrule) you have to create a new Time object and set it to your EventRecurrence object. I wasn't doing that also, that's the reason why it kept crashing. Here's a small part of my code:

@Override
public void onRecurrenceSet(String rrule) {
   if (rrule != null) {
      evtRec.parse(rrule);
      Time startDate = new Time(timeZone.getID());
      startDate.set(monthDay, month, year);
      startDate.normalize(true);
      evtRec.setStartDate(startDate);
   }
   populateRepeats();
}

**Comment by bbbenja** [comment]
see #139
