### ISSUE TITLE
Conflict Gradle with android-switch-backport

### ISSUE THREAD

**Issue by syrineT** [code-troopers/android-betterpickers#85]
I have a conflict with android-switch-backport and android-betterpickers because both override the style "switchStyle" and "switchPreferenceStyle". 
I want to use both of libraries (for the switch android-switch-backport have more possibilities )

I'm using android-studio . my app is supporting Android Api 10 .
If anyone have an idea of how i can resolve this conflict ...

Can you please put a prefix to your styles ?

**Comment by depodefi** [comment]
Same problem for me. It would be better if you could user gradle dependency in android-betterpikers lib project instead hardcoding it. Than it would be possible to exclude android-switch-backport  dependency.

**Comment by Volkanugr** [comment]
my problem is not understanding 

```
compile fileTree(dir: 'libs', include: ['*.jar'])
compile 'com.github.dmytrodanylyk.circular-progress-button:library:1.0.4'
compile 'info.hoang8f:fbutton:1.0.4'
compile 'com.romainpiel.shimmer:library:1.2.0@aar'
compile 'com.nhaarman.listviewanimations:library:2.6.0'
compile 'com.readystatesoftware.sqliteasset:sqliteassethelper:+'
compile 'com.actionbarsherlock:actionbarsherlock:4.4.0@aar'
```

and everything is gook working 

add     compile 'com.doomonafireball.betterpickers:library:1.5.2'

eg my application stopped to work on create FATAL EROR EXECPTION why ?

**Comment by BraisGabin** [comment]
Same problem with HoloEverywhere and BetterPickers

**Comment by chelexey** [comment]
> eg my application stopped to work on create FATAL EROR EXECPTION why ?

Try the following in build.gradle:

```
compile('com.doomonafireball.betterpickers:library:1.5.3') {
        exclude group: 'com.android.support', module: 'support-v4'
        exclude group: 'com.nineoldandroids', module: 'library'
    }
```

**Comment by bbbenja** [comment]
On 1.5.3, "switchStyle" and "switchPreferenceStyle" are prefixed, so you will not have this error anymore. You can reopen this issue if not.
