### ISSUE TITLE
Dialogs crashing when trying to show

### ISSUE THREAD

**Issue by holtn** [code-troopers/android-betterpickers#93]
I keep getting an layout crash to do with an Error inflating the class com.doomonafireball.betterpickers.datepicker.DatePicker.

I can't seem to get any of the dialogs to work.
Im adding the library to eclipse and then adding it to my project, it seems to have a lot of problems though, I had to update the Support library, add nineoldsandroid, compile it with a newer version of android and set it up to run as a library, then after fixing the font bug in the styles I've run into this one, why is there so many problems? am i doing something wrong? 

Any help would be great because this looks like an amazing piece of code, when it works.

Heres my Logcat of the problem:

06-09 17:58:05.149: E/AndroidRuntime(22984): FATAL EXCEPTION: main
06-09 17:58:05.149: E/AndroidRuntime(22984): Process: com.tekmeld.svb2269
06-09 17:58:05.149: E/AndroidRuntime(22984): android.view.InflateException: Binary XML file line #7: Error inflating class com.doomonafireball.betterpickers.datepicker.DatePicker
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.view.LayoutInflater.createView(LayoutInflater.java:626)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at com.doomonafireball.betterpickers.datepicker.DatePickerDialogFragment.onCreateView(DatePickerDialogFragment.java:126)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.support.v4.app.Fragment.performCreateView(Fragment.java:1500)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:927)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:440)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.os.Handler.handleCallback(Handler.java:733)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.os.Handler.dispatchMessage(Handler.java:95)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.os.Looper.loop(Looper.java:157)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.app.ActivityThread.main(ActivityThread.java:5356)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at java.lang.reflect.Method.invokeNative(Native Method)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at java.lang.reflect.Method.invoke(Method.java:515)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at dalvik.system.NativeStart.main(Native Method)
06-09 17:58:05.149: E/AndroidRuntime(22984): Caused by: java.lang.reflect.InvocationTargetException
06-09 17:58:05.149: E/AndroidRuntime(22984):    at java.lang.reflect.Constructor.constructNative(Native Method)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.view.LayoutInflater.createView(LayoutInflater.java:600)
06-09 17:58:05.149: E/AndroidRuntime(22984):    ... 21 more
06-09 17:58:05.149: E/AndroidRuntime(22984): Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class com.doomonafireball.betterpickers.datepicker.DateView
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.view.LayoutInflater.createView(LayoutInflater.java:626)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at com.doomonafireball.betterpickers.datepicker.DatePicker.<init>(DatePicker.java:98)
06-09 17:58:05.149: E/AndroidRuntime(22984):    ... 24 more
06-09 17:58:05.149: E/AndroidRuntime(22984): Caused by: java.lang.reflect.InvocationTargetException
06-09 17:58:05.149: E/AndroidRuntime(22984):    at java.lang.reflect.Constructor.constructNative(Native Method)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.view.LayoutInflater.createView(LayoutInflater.java:600)
06-09 17:58:05.149: E/AndroidRuntime(22984):    ... 31 more
06-09 17:58:05.149: E/AndroidRuntime(22984): Caused by: java.lang.RuntimeException: native typeface cannot be made
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.graphics.Typeface.<init>(Typeface.java:325)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at android.graphics.Typeface.createFromAsset(Typeface.java:299)
06-09 17:58:05.149: E/AndroidRuntime(22984):    at com.doomonafireball.betterpickers.datepicker.DateView.<init>(DateView.java:47)
06-09 17:58:05.149: E/AndroidRuntime(22984):    ... 34 more

**Comment by mikebell90** [comment]
This is because you are using Eclipse instead of Android Studio. The assets folder therefore is not copied automatically. Copy the assets folder from the betterdatepicker project into your main app if you want to keep using eclipse.

**Comment by drupalmav** [comment]
copied the assets folder but still getting the xml error on the same line #7, anything else one can try?
